<?php

namespace App\Tutorial;

class JsTopics
{
    public static function getTopics(): array
    {
        return [
            [
                'category' => 'JS Tutorial',
                'items' => [
                    ['slug' => 'home', 'title' => 'JS Home', 'desc' => 'Introduction to JavaScript'],
                    ['slug' => 'intro', 'title' => 'JS Introduction', 'desc' => 'JavaScript Introduction'],
                    ['slug' => 'whereto', 'title' => 'JS Where To', 'desc' => 'Where to put JavaScript'],
                    ['slug' => 'output', 'title' => 'JS Output', 'desc' => 'JavaScript Output'],
                    ['slug' => 'syntax', 'title' => 'JS Syntax', 'desc' => 'JavaScript Syntax'],
                    ['slug' => 'statements', 'title' => 'Statements', 'desc' => 'JavaScript Statements'],
                    ['slug' => 'comments', 'title' => 'Comments', 'desc' => 'JavaScript Comments'],
                    ['slug' => 'variables', 'title' => 'Variables', 'desc' => 'JavaScript Variables'],
                    ['slug' => 'let', 'title' => 'Let', 'desc' => 'JavaScript Let'],
                    ['slug' => 'const', 'title' => 'Const', 'desc' => 'JavaScript Const'],
                    ['slug' => 'types', 'title' => 'Types', 'desc' => 'JavaScript Types'],
                    ['slug' => 'operators', 'title' => 'JS Operators', 'desc' => 'JavaScript Operators'],
                    ['slug' => 'arithmetic', 'title' => 'Arithmetic', 'desc' => 'JavaScript Arithmetic'],
                    ['slug' => 'assignment', 'title' => 'Assignment', 'desc' => 'JavaScript Assignment'],
                    ['slug' => 'comparisons', 'title' => 'Comparisons', 'desc' => 'JavaScript Comparisons'],
                    ['slug' => 'conditional', 'title' => 'Conditional', 'desc' => 'JavaScript Conditional'],
                    ['slug' => 'if', 'title' => 'JS If Conditions', 'desc' => 'JavaScript If Conditions'],
                    ['slug' => 'if-else', 'title' => 'If Else', 'desc' => 'JavaScript If Else'],
                    ['slug' => 'ternary', 'title' => 'Ternary', 'desc' => 'JavaScript Ternary'],
                    ['slug' => 'switch', 'title' => 'Switch', 'desc' => 'JavaScript Switch'],
                    ['slug' => 'booleans', 'title' => 'Booleans', 'desc' => 'JavaScript Booleans'],
                    ['slug' => 'logical', 'title' => 'Logical', 'desc' => 'JavaScript Logical'],
                    ['slug' => 'loops', 'title' => 'JS Loops', 'desc' => 'JavaScript Loops'],
                    ['slug' => 'for', 'title' => 'for', 'desc' => 'JavaScript for loop'],
                    ['slug' => 'while', 'title' => 'while', 'desc' => 'JavaScript while loop'],
                    ['slug' => 'break', 'title' => 'Break', 'desc' => 'JavaScript Break'],
                    ['slug' => 'continue', 'title' => 'Continue', 'desc' => 'JavaScript Continue'],
                    ['slug' => 'control-flow', 'title' => 'Control Flow', 'desc' => 'JavaScript Control Flow'],
                    ['slug' => 'strings', 'title' => 'JS Strings', 'desc' => 'JavaScript Strings'],
                    ['slug' => 'string-templates', 'title' => 'Templates', 'desc' => 'JavaScript String Templates'],
                    ['slug' => 'string-methods', 'title' => 'Methods', 'desc' => 'JavaScript String Methods'],
                    ['slug' => 'string-search', 'title' => 'Search', 'desc' => 'JavaScript String Search'],
                    ['slug' => 'numbers', 'title' => 'JS Numbers', 'desc' => 'JavaScript Numbers'],
                    ['slug' => 'number-methods', 'title' => 'Methods', 'desc' => 'JavaScript Number Methods'],
                    ['slug' => 'number-properties', 'title' => 'Properties', 'desc' => 'JavaScript Number Properties'],
                    ['slug' => 'bitwise', 'title' => 'Bitwise', 'desc' => 'JavaScript Bitwise'],
                    ['slug' => 'bigint', 'title' => 'BigInt', 'desc' => 'JavaScript BigInt'],
                    ['slug' => 'functions', 'title' => 'JS Functions', 'desc' => 'JavaScript Functions'],
                    ['slug' => 'function-intro', 'title' => 'Intro', 'desc' => 'JavaScript Function Intro'],
                    ['slug' => 'function-invocation', 'title' => 'Invocation', 'desc' => 'JavaScript Function Invocation'],
                    ['slug' => 'function-parameters', 'title' => 'Parameters', 'desc' => 'JavaScript Function Parameters'],
                    ['slug' => 'function-returns', 'title' => 'Returns', 'desc' => 'JavaScript Function Returns'],
                    ['slug' => 'function-arguments', 'title' => 'Arguments', 'desc' => 'JavaScript Function Arguments'],
                    ['slug' => 'function-expressions', 'title' => 'Expressions', 'desc' => 'JavaScript Function Expressions'],
                    ['slug' => 'arrow-functions', 'title' => 'Arrow', 'desc' => 'JavaScript Arrow Functions'],
                    ['slug' => 'timers', 'title' => 'JS Timers', 'desc' => 'JavaScript Timers'],
                    ['slug' => 'objects', 'title' => 'JS Objects', 'desc' => 'JavaScript Objects'],
                    ['slug' => 'object-intro', 'title' => 'Intro', 'desc' => 'JavaScript Object Intro'],
                    ['slug' => 'object-properties', 'title' => 'Properties', 'desc' => 'JavaScript Object Properties'],
                    ['slug' => 'object-methods', 'title' => 'Methods', 'desc' => 'JavaScript Object Methods'],
                    ['slug' => 'object-this', 'title' => 'this', 'desc' => 'JavaScript Object this'],
                    ['slug' => 'object-display', 'title' => 'Display', 'desc' => 'JavaScript Object Display'],
                    ['slug' => 'object-constructors', 'title' => 'Constructors', 'desc' => 'JavaScript Object Constructors'],
                    ['slug' => 'scope', 'title' => 'JS Scope', 'desc' => 'JavaScript Scope'],
                    ['slug' => 'code-blocks', 'title' => 'Code Blocks', 'desc' => 'JavaScript Code Blocks'],
                    ['slug' => 'hoisting', 'title' => 'Hoisting', 'desc' => 'JavaScript Hoisting'],
                    ['slug' => 'var-let-const', 'title' => 'var/let/const', 'desc' => 'JavaScript var/let/const'],
                    ['slug' => 'strict-mode', 'title' => 'Strict Mode', 'desc' => 'JavaScript Strict Mode'],
                    ['slug' => 'dates', 'title' => 'JS Dates', 'desc' => 'JavaScript Dates'],
                    ['slug' => 'date-formats', 'title' => 'Formats', 'desc' => 'JavaScript Date Formats'],
                    ['slug' => 'date-get', 'title' => 'Get', 'desc' => 'JavaScript Date Get'],
                    ['slug' => 'date-set', 'title' => 'Set', 'desc' => 'JavaScript Date Set'],
                    ['slug' => 'date-methods', 'title' => 'Methods', 'desc' => 'JavaScript Date Methods'],
                    ['slug' => 'temporal', 'title' => 'JS Temporal', 'desc' => 'JavaScript Temporal'],
                    ['slug' => 'temporal-intro', 'title' => 'Intro', 'desc' => 'Temporal Intro'],
                    ['slug' => 'temporal-vs-date', 'title' => 'vs Date', 'desc' => 'Temporal vs Date'],
                    ['slug' => 'duration', 'title' => 'Duration', 'desc' => 'Temporal Duration'],
                    ['slug' => 'instant', 'title' => 'Instant', 'desc' => 'Temporal Instant'],
                    ['slug' => 'plaindatetime', 'title' => 'PlainDateTime', 'desc' => 'Temporal PlainDateTime'],
                    ['slug' => 'plaindate', 'title' => 'PlainDate', 'desc' => 'Temporal PlainDate'],
                    ['slug' => 'plainyearmonth', 'title' => 'PlainYearMonth', 'desc' => 'Temporal PlainYearMonth'],
                    ['slug' => 'plainmonthday', 'title' => 'PlainMonthDay', 'desc' => 'Temporal PlainMonthDay'],
                    ['slug' => 'plaintime', 'title' => 'PlainTime', 'desc' => 'Temporal PlainTime'],
                    ['slug' => 'zoneddate', 'title' => 'ZonedDate', 'desc' => 'Temporal ZonedDate'],
                    ['slug' => 'now', 'title' => 'Now', 'desc' => 'Temporal Now'],
                    ['slug' => 'temporal-arithmetic', 'title' => 'Arithmetic', 'desc' => 'Temporal Arithmetic'],
                    ['slug' => 'temporal-since-until', 'title' => 'Since/Until', 'desc' => 'Temporal Since/Until'],
                    ['slug' => 'temporal-compare', 'title' => 'Compare', 'desc' => 'Temporal Compare'],
                    ['slug' => 'temporal-conversion', 'title' => 'Conversion', 'desc' => 'Temporal Conversion'],
                    ['slug' => 'temporal-formats', 'title' => 'Formats', 'desc' => 'Temporal Formats'],
                    ['slug' => 'temporal-mistakes', 'title' => 'Mistakes', 'desc' => 'Temporal Mistakes'],
                    ['slug' => 'temporal-migrate', 'title' => 'Migrate', 'desc' => 'Temporal Migrate'],
                    ['slug' => 'temporal-standards', 'title' => 'Standards', 'desc' => 'Temporal Standards'],
                    ['slug' => 'arrays', 'title' => 'JS Arrays', 'desc' => 'JavaScript Arrays'],
                    ['slug' => 'array-constructor', 'title' => 'Constructor', 'desc' => 'JavaScript Array Constructor'],
                    ['slug' => 'array-methods', 'title' => 'Methods', 'desc' => 'JavaScript Array Methods'],
                    ['slug' => 'array-search', 'title' => 'Search', 'desc' => 'JavaScript Array Search'],
                    ['slug' => 'array-sort', 'title' => 'Sort', 'desc' => 'JavaScript Array Sort'],
                    ['slug' => 'array-iterations', 'title' => 'Iterations', 'desc' => 'JavaScript Array Iterations'],
                    ['slug' => 'array-const', 'title' => 'const', 'desc' => 'JavaScript Array const'],
                    ['slug' => 'sets', 'title' => 'JS Sets', 'desc' => 'JavaScript Sets'],
                    ['slug' => 'set-methods', 'title' => 'Methods', 'desc' => 'JavaScript Set Methods'],
                    ['slug' => 'set-logic', 'title' => 'Logic', 'desc' => 'JavaScript Set Logic'],
                    ['slug' => 'weakset', 'title' => 'WeakSet', 'desc' => 'JavaScript WeakSet'],
                    ['slug' => 'maps', 'title' => 'JS Maps', 'desc' => 'JavaScript Maps'],
                    ['slug' => 'map-methods', 'title' => 'Methods', 'desc' => 'JavaScript Map Methods'],
                    ['slug' => 'weakmap', 'title' => 'WeakMap', 'desc' => 'JavaScript WeakMap'],
                    ['slug' => 'iterations', 'title' => 'JS Iterations', 'desc' => 'JavaScript Iterations'],
                    ['slug' => 'iteration-loops', 'title' => 'Loops', 'desc' => 'Iteration Loops'],
                    ['slug' => 'iterables', 'title' => 'Iterables', 'desc' => 'Iterables'],
                    ['slug' => 'iterators', 'title' => 'Iterators', 'desc' => 'Iterators'],
                    ['slug' => 'generators', 'title' => 'Generators', 'desc' => 'Generators'],
                    ['slug' => 'math', 'title' => 'JS Math', 'desc' => 'JavaScript Math'],
                    ['slug' => 'math-random', 'title' => 'Random', 'desc' => 'JavaScript Math Random'],
                    ['slug' => 'regexp', 'title' => 'JS RegExp', 'desc' => 'JavaScript RegExp'],
                    ['slug' => 'regexp-flags', 'title' => 'Flags', 'desc' => 'RegExp Flags'],
                    ['slug' => 'regexp-classes', 'title' => 'Classes', 'desc' => 'RegExp Classes'],
                    ['slug' => 'regexp-metachars', 'title' => 'Metachars', 'desc' => 'RegExp Metachars'],
                    ['slug' => 'regexp-assertions', 'title' => 'Assertions', 'desc' => 'RegExp Assertions'],
                    ['slug' => 'regexp-groups', 'title' => 'Groups', 'desc' => 'RegExp Groups'],
                    ['slug' => 'regexp-quantifiers', 'title' => 'Quantifiers', 'desc' => 'RegExp Quantifiers'],
                    ['slug' => 'regexp-patterns', 'title' => 'Patterns', 'desc' => 'RegExp Patterns'],
                    ['slug' => 'regexp-objects', 'title' => 'Objects', 'desc' => 'RegExp Objects'],
                    ['slug' => 'regexp-methods', 'title' => 'Methods', 'desc' => 'RegExp Methods'],
                    ['slug' => 'data-types', 'title' => 'JS Data Types', 'desc' => 'JavaScript Data Types'],
                    ['slug' => 'primitives', 'title' => 'Primitives', 'desc' => 'JavaScript Primitives'],
                    ['slug' => 'object-types', 'title' => 'Object Types', 'desc' => 'JavaScript Object Types'],
                    ['slug' => 'symbols', 'title' => 'Symbols', 'desc' => 'JavaScript Symbols'],
                    ['slug' => 'typeof', 'title' => 'typeof', 'desc' => 'JavaScript typeof'],
                    ['slug' => 'undefined', 'title' => 'undefined', 'desc' => 'JavaScript undefined'],
                    ['slug' => 'nan', 'title' => 'NaN', 'desc' => 'JavaScript NaN'],
                    ['slug' => 'tostring', 'title' => 'toString', 'desc' => 'JavaScript toString'],
                    ['slug' => 'tolocalestring', 'title' => 'toLocaleString', 'desc' => 'JavaScript toLocaleString'],
                    ['slug' => 'type-coercion', 'title' => 'Type Coercion', 'desc' => 'JavaScript Type Coercion'],
                    ['slug' => 'type-conversion', 'title' => 'Conversion', 'desc' => 'JavaScript Type Conversion'],
                    ['slug' => 'destructuring', 'title' => 'Destructuring', 'desc' => 'JavaScript Destructuring'],
                    ['slug' => 'errors', 'title' => 'JS Errors', 'desc' => 'JavaScript Errors'],
                    ['slug' => 'error-intro', 'title' => 'Intro', 'desc' => 'Error Intro'],
                    ['slug' => 'error-silent', 'title' => 'Silent', 'desc' => 'Silent Errors'],
                    ['slug' => 'error-statements', 'title' => 'Statements', 'desc' => 'Error Statements'],
                    ['slug' => 'error-object', 'title' => 'Object', 'desc' => 'Error Object'],
                    ['slug' => 'debugging', 'title' => 'JS Debugging', 'desc' => 'JavaScript Debugging'],
                    ['slug' => 'debugging-console', 'title' => 'Console', 'desc' => 'Debugging Console'],
                    ['slug' => 'debugging-breakpoints', 'title' => 'Breakpoints', 'desc' => 'Debugging Breakpoints'],
                    ['slug' => 'debugging-errors', 'title' => 'Errors', 'desc' => 'Debugging Errors'],
                    ['slug' => 'debugging-async', 'title' => 'Async', 'desc' => 'Debugging Async'],
                    ['slug' => 'style-guide', 'title' => 'JS Style Guide', 'desc' => 'JavaScript Style Guide'],
                    ['slug' => 'best-practices', 'title' => 'Best Practices', 'desc' => 'Best Practices'],
                    ['slug' => 'mistakes', 'title' => 'Mistakes', 'desc' => 'Common Mistakes'],
                    ['slug' => 'performance', 'title' => 'Performance', 'desc' => 'Performance'],
                    ['slug' => 'projects', 'title' => 'JS Projects', 'desc' => 'JavaScript Projects'],
                    ['slug' => 'project-counter', 'title' => 'Counter', 'desc' => 'Counter Project'],
                    ['slug' => 'project-event-listener', 'title' => 'Event Listener', 'desc' => 'Event Listener Project'],
                    ['slug' => 'project-todo', 'title' => 'To-Do', 'desc' => 'To-Do Project'],
                    ['slug' => 'project-modal', 'title' => 'Modal Popup', 'desc' => 'Modal Popup Project'],
                    ['slug' => 'project-form-validation', 'title' => 'Form Validation', 'desc' => 'Form Validation Project'],
                    ['slug' => 'versions', 'title' => 'JS Versions', 'desc' => 'JavaScript Versions'],
                    ['slug' => 'versions-2027-2009', 'title' => '2027-2009', 'desc' => 'Versions 2027-2009'],
                    ['slug' => 'es6', 'title' => 'ES6', 'desc' => 'ES6'],
                    ['slug' => 'es5', 'title' => 'ES5', 'desc' => 'ES5'],
                    ['slug' => 'es3', 'title' => 'ES3', 'desc' => 'ES3'],
                    ['slug' => 'history', 'title' => 'History', 'desc' => 'History'],
                ]
            ],
            [
                'category' => 'JS Advanced',
                'items' => [
                    ['slug' => 'dom', 'title' => 'JS HTML DOM', 'desc' => 'JS HTML DOM'],
                    ['slug' => 'dom-api', 'title' => 'API', 'desc' => 'DOM API'],
                    ['slug' => 'dom-selecting', 'title' => 'Selecting Elements', 'desc' => 'Selecting Elements'],
                    ['slug' => 'dom-changing-html', 'title' => 'Changing HTML', 'desc' => 'Changing HTML'],
                    ['slug' => 'dom-changing-css', 'title' => 'Changing CSS', 'desc' => 'Changing CSS'],
                    ['slug' => 'dom-form-validation', 'title' => 'Form Validation', 'desc' => 'Form Validation'],
                    ['slug' => 'dom-animations', 'title' => 'Animations', 'desc' => 'DOM Animations'],
                    ['slug' => 'events', 'title' => 'JS HTML Events', 'desc' => 'JS HTML Events'],
                    ['slug' => 'event-mouse', 'title' => 'Mouse', 'desc' => 'Mouse Events'],
                    ['slug' => 'event-keyboard', 'title' => 'Keyboard', 'desc' => 'Keyboard Events'],
                    ['slug' => 'event-load', 'title' => 'Load', 'desc' => 'Load Events'],
                    ['slug' => 'event-manage', 'title' => 'Manage', 'desc' => 'Manage Events'],
                    ['slug' => 'event-examples', 'title' => 'Examples', 'desc' => 'Event Examples'],
                    ['slug' => 'event-listener', 'title' => 'Listener', 'desc' => 'Event Listener'],
                    ['slug' => 'html-first', 'title' => 'JS HTML First', 'desc' => 'JS HTML First'],
                    ['slug' => 'progressive', 'title' => 'Progressive', 'desc' => 'Progressive'],
                    ['slug' => 'features', 'title' => 'Features', 'desc' => 'Features'],
                    ['slug' => 'html-first-css', 'title' => 'CSS', 'desc' => 'HTML First CSS'],
                    ['slug' => 'functions-advanced', 'title' => 'JS Functions Advanced', 'desc' => 'JS Functions Advanced'],
                    ['slug' => 'function-definitions', 'title' => 'Definitions', 'desc' => 'Function Definitions'],
                    ['slug' => 'function-callbacks', 'title' => 'Callbacks', 'desc' => 'Function Callbacks'],
                    ['slug' => 'function-this', 'title' => 'this', 'desc' => 'Function this'],
                    ['slug' => 'function-call', 'title' => 'Call', 'desc' => 'Function Call'],
                    ['slug' => 'function-apply', 'title' => 'Apply', 'desc' => 'Function Apply'],
                    ['slug' => 'function-bind', 'title' => 'Bind', 'desc' => 'Function Bind'],
                    ['slug' => 'function-iife', 'title' => 'IIFE', 'desc' => 'Function IIFE'],
                    ['slug' => 'function-closures', 'title' => 'Closures', 'desc' => 'Function Closures'],
                    ['slug' => 'objects-advanced', 'title' => 'JS Objects Advanced', 'desc' => 'JS Objects Advanced'],
                    ['slug' => 'object-definitions', 'title' => 'Definitions', 'desc' => 'Object Definitions'],
                    ['slug' => 'object-advanced-this', 'title' => 'this', 'desc' => 'Object this'],
                    ['slug' => 'object-iterations', 'title' => 'Iterations', 'desc' => 'Object Iterations'],
                    ['slug' => 'object-get-set', 'title' => 'Get/Set', 'desc' => 'Object Get/Set'],
                    ['slug' => 'object-management', 'title' => 'Management', 'desc' => 'Object Management'],
                    ['slug' => 'object-protection', 'title' => 'Protection', 'desc' => 'Object Protection'],
                    ['slug' => 'object-prototypes', 'title' => 'Prototypes', 'desc' => 'Object Prototypes'],
                    ['slug' => 'classes', 'title' => 'JS Classes', 'desc' => 'JS Classes'],
                    ['slug' => 'class-inheritance', 'title' => 'Inheritance', 'desc' => 'Class Inheritance'],
                    ['slug' => 'class-static', 'title' => 'Static', 'desc' => 'Class Static'],
                    ['slug' => 'json', 'title' => 'JS JSON', 'desc' => 'JS JSON'],
                    ['slug' => 'json-syntax', 'title' => 'Syntax', 'desc' => 'JSON Syntax'],
                    ['slug' => 'json-values', 'title' => 'Values', 'desc' => 'JSON Values'],
                    ['slug' => 'json-parse', 'title' => 'Parse', 'desc' => 'JSON Parse'],
                    ['slug' => 'json-stringify', 'title' => 'Stringify', 'desc' => 'JSON Stringify'],
                    ['slug' => 'json-fetch', 'title' => 'Fetch', 'desc' => 'JSON Fetch'],
                    ['slug' => 'json-html', 'title' => 'HTML', 'desc' => 'JSON HTML'],
                    ['slug' => 'json-vs-xml', 'title' => 'vs XML', 'desc' => 'JSON vs XML'],
                    ['slug' => 'async', 'title' => 'JS Asynchronous', 'desc' => 'JS Asynchronous'],
                    ['slug' => 'async-programming', 'title' => 'Programming', 'desc' => 'Async Programming'],
                    ['slug' => 'async-callbacks', 'title' => 'Callbacks', 'desc' => 'Async Callbacks'],
                    ['slug' => 'async-promises', 'title' => 'Promises', 'desc' => 'Async Promises'],
                    ['slug' => 'async-await', 'title' => 'Await', 'desc' => 'Async Await'],
                    ['slug' => 'async-parallel', 'title' => 'Parallel', 'desc' => 'Async Parallel'],
                    ['slug' => 'async-event-loop', 'title' => 'Event Loop', 'desc' => 'Event Loop'],
                    ['slug' => 'fetch', 'title' => 'Fetch API', 'desc' => 'Fetch API'],
                    ['slug' => 'async-mistakes', 'title' => 'Mistakes', 'desc' => 'Async Mistakes'],
                    ['slug' => 'async-debugging', 'title' => 'Debugging', 'desc' => 'Async Debugging'],
                    ['slug' => 'async-abortcontroller', 'title' => 'AbortController', 'desc' => 'AbortController'],
                    ['slug' => 'async-web-workers', 'title' => 'Web Workers', 'desc' => 'Web Workers'],
                    ['slug' => 'modules', 'title' => 'JS Modules', 'desc' => 'JS Modules'],
                    ['slug' => 'module-export', 'title' => 'Export', 'desc' => 'Module Export'],
                    ['slug' => 'module-import', 'title' => 'Import', 'desc' => 'Module Import'],
                    ['slug' => 'module-namespace', 'title' => 'Namespace', 'desc' => 'Module Namespace'],
                    ['slug' => 'module-dynamic', 'title' => 'Dynamic', 'desc' => 'Module Dynamic'],
                    ['slug' => 'meta-proxy', 'title' => 'JS Meta & Proxy', 'desc' => 'JS Meta & Proxy'],
                    ['slug' => 'meta-reflect', 'title' => 'Reflect', 'desc' => 'Reflect'],
                    ['slug' => 'meta-proxy-object', 'title' => 'Proxy', 'desc' => 'Proxy Object'],
                    ['slug' => 'typed-arrays', 'title' => 'JS Typed Arrays', 'desc' => 'JS Typed Arrays'],
                    ['slug' => 'typed-array-methods', 'title' => 'Methods', 'desc' => 'Typed Array Methods'],
                    ['slug' => 'array-buffers', 'title' => 'Array Buffers', 'desc' => 'Array Buffers'],
                    ['slug' => 'dataviews', 'title' => 'DataViews', 'desc' => 'DataViews'],
                    ['slug' => 'atomics', 'title' => 'Atomics', 'desc' => 'Atomics'],
                    ['slug' => 'dom-navigation', 'title' => 'JS DOM Navigation', 'desc' => 'JS DOM Navigation'],
                    ['slug' => 'dom-nodes', 'title' => 'Nodes', 'desc' => 'DOM Nodes'],
                    ['slug' => 'dom-collections', 'title' => 'Collections', 'desc' => 'DOM Collections'],
                    ['slug' => 'dom-node-lists', 'title' => 'Node Lists', 'desc' => 'DOM Node Lists'],
                    ['slug' => 'browser-api', 'title' => 'JS Browser API', 'desc' => 'JS Browser API'],
                    ['slug' => 'browser-window', 'title' => 'Window', 'desc' => 'Browser Window'],
                    ['slug' => 'browser-screen', 'title' => 'Screen', 'desc' => 'Browser Screen'],
                    ['slug' => 'browser-location', 'title' => 'Location', 'desc' => 'Browser Location'],
                    ['slug' => 'browser-history', 'title' => 'History', 'desc' => 'Browser History'],
                    ['slug' => 'browser-navigator', 'title' => 'Navigator', 'desc' => 'Browser Navigator'],
                    ['slug' => 'browser-popup', 'title' => 'Popup', 'desc' => 'Browser Popup'],
                    ['slug' => 'browser-cookies', 'title' => 'Cookies', 'desc' => 'Browser Cookies'],
                    ['slug' => 'web-api', 'title' => 'JS Web API', 'desc' => 'JS Web API'],
                    ['slug' => 'web-api-intro', 'title' => 'Intro', 'desc' => 'Web API Intro'],
                    ['slug' => 'web-api-fetch', 'title' => 'Fetch', 'desc' => 'Web API Fetch'],
                    ['slug' => 'web-api-geolocation', 'title' => 'Geolocation', 'desc' => 'Web API Geolocation'],
                    ['slug' => 'web-api-history', 'title' => 'History', 'desc' => 'Web API History'],
                    ['slug' => 'web-api-pointer', 'title' => 'Pointer', 'desc' => 'Web API Pointer'],
                    ['slug' => 'web-api-storage', 'title' => 'Storage', 'desc' => 'Web API Storage'],
                    ['slug' => 'web-api-validation', 'title' => 'Validation', 'desc' => 'Web API Validation'],
                    ['slug' => 'web-api-worker', 'title' => 'Worker', 'desc' => 'Web API Worker'],
                    ['slug' => 'graphics', 'title' => 'JS Graphics', 'desc' => 'JS Graphics'],
                    ['slug' => 'canvas', 'title' => 'Canvas', 'desc' => 'Canvas'],
                    ['slug' => 'plotly', 'title' => 'Plotly', 'desc' => 'Plotly'],
                    ['slug' => 'chartjs', 'title' => 'Chart.js', 'desc' => 'Chart.js'],
                    ['slug' => 'google-chart', 'title' => 'Google Chart', 'desc' => 'Google Chart'],
                    ['slug' => 'd3js', 'title' => 'D3.js', 'desc' => 'D3.js'],
                    ['slug' => 'ajax', 'title' => 'JS AJAX', 'desc' => 'JS AJAX'],
                    ['slug' => 'ajax-intro', 'title' => 'Intro', 'desc' => 'AJAX Intro'],
                    ['slug' => 'ajax-xmlhttp', 'title' => 'XMLHttp', 'desc' => 'AJAX XMLHttp'],
                    ['slug' => 'ajax-request', 'title' => 'Request', 'desc' => 'AJAX Request'],
                    ['slug' => 'ajax-response', 'title' => 'Response', 'desc' => 'AJAX Response'],
                    ['slug' => 'ajax-xml-file', 'title' => 'XML File', 'desc' => 'AJAX XML File'],
                    ['slug' => 'ajax-php', 'title' => 'PHP', 'desc' => 'AJAX PHP'],
                    ['slug' => 'ajax-asp', 'title' => 'ASP', 'desc' => 'AJAX ASP'],
                    ['slug' => 'ajax-database', 'title' => 'Database', 'desc' => 'AJAX Database'],
                    ['slug' => 'ajax-applications', 'title' => 'Applications', 'desc' => 'AJAX Applications'],
                    ['slug' => 'ajax-examples', 'title' => 'Examples', 'desc' => 'AJAX Examples'],
                    ['slug' => 'jquery', 'title' => 'JS jQuery', 'desc' => 'JS jQuery'],
                    ['slug' => 'jquery-selectors', 'title' => 'Selectors', 'desc' => 'jQuery Selectors'],
                    ['slug' => 'jquery-html', 'title' => 'HTML', 'desc' => 'jQuery HTML'],
                    ['slug' => 'jquery-css', 'title' => 'CSS', 'desc' => 'jQuery CSS'],
                    ['slug' => 'jquery-dom', 'title' => 'DOM', 'desc' => 'jQuery DOM'],
                    ['slug' => 'jsonp', 'title' => 'JS JSONP', 'desc' => 'JS JSONP'],
                ]
            ],
        ];
    }

    public static function getTopicContent(string $slug): ?array
    {
        $map = [
            'output' => [
                'code' => "document.getElementById('demo').innerHTML = 'Hello World';\nconsole.log(5 + 6);",
                'question' => 'Use console.log to output the number 11.',
                'prefix' => "console.",
                'suffix' => "(11);",
                'answer' => "log"
            ],
            'syntax' => [
                'code' => "let x, y, z;  // Statement 1\nx = 5;        // Statement 2\ny = 6;        // Statement 3\nz = x + y;    // Statement 4",
                'question' => 'Create a variable using the let keyword.',
                'prefix' => "",
                'suffix' => " a = 10;",
                'answer' => "let"
            ],
            'variables' => [
                'code' => "var x = 5;\nlet y = 6;\nconst z = 7;",
                'question' => 'Create a variable named carName and assign the value "Volvo" to it.',
                'prefix' => "let ",
                'suffix' => " = 'Volvo';",
                'answer' => "carName"
            ],
            'operators' => [
                'code' => "let x = 5;\nlet y = 2;\nlet z = x * y;",
                'question' => 'Multiply 10 with 5, and alert the result:',
                'prefix' => "alert(10 ",
                'suffix' => " 5);",
                'answer' => "*"
            ],
            'if' => [
                'code' => "if (time < 20) {\n  greeting = 'Good day';\n}",
                'question' => 'Create an if statement that will alert "Hello World" if x is greater than y.',
                'prefix' => "",
                'suffix' => " (x > y) {\n  alert('Hello World');\n}",
                'answer' => "if"
            ],
            'loops' => [
                'code' => "for (let i = 0; i < 5; i++) {\n  text += 'The number is ' + i + '\\n';\n}",
                'question' => 'Create a for loop that runs from 0 to 9.',
                'prefix' => "for (let i = 0; i ",
                'suffix' => " 10; i++) {}",
                'answer' => "<"
            ],
            'strings' => [
                'code' => "let text = 'John Doe';\nlet length = text.length;",
                'question' => 'Find the length of the string str1.',
                'prefix' => "let x = str1.",
                'suffix' => ";",
                'answer' => "length"
            ],
            'functions' => [
                'code' => "function myFunction(p1, p2) {\n  return p1 * p2;\n}",
                'question' => 'Execute the function named myFunction.',
                'prefix' => "",
                'suffix' => "();",
                'answer' => "myFunction"
            ],
            'arrays' => [
                'code' => "const cars = ['Saab', 'Volvo', 'BMW'];\nlet car = cars[0];",
                'question' => 'Get the value "Volvo" from the cars array.',
                'prefix' => "let x = cars[",
                'suffix' => "];",
                'answer' => "1"
            ],
            'objects' => [
                'code' => "const person = {\n  firstName: 'John',\n  lastName: 'Doe',\n  age: 50\n};",
                'question' => 'Access the firstName property of the person object.',
                'prefix' => "let name = person.",
                'suffix' => ";",
                'answer' => "firstName"
            ],
            'dom' => [
                'code' => "document.getElementById('demo').innerHTML = 'Hello World!';",
                'question' => 'Use the getElementById method to find the <p> element, and change its text to "Hello".',
                'prefix' => "document.getElementById('demo').",
                'suffix' => " = 'Hello';",
                'answer' => "innerHTML"
            ],
            'events' => [
                'code' => "<button onclick=\"displayDate()\">The time is?</button>",
                'question' => 'Add an onclick event to the button that runs the displayDate function.',
                'prefix' => "<button ",
                'suffix' => "=\"displayDate()\">Click</button>",
                'answer' => "onclick"
            ],
            'async' => [
                'code' => "setTimeout(function() { myFunction('I love You !!!'); }, 3000);",
                'question' => 'Call the myFunction function after 2 seconds.',
                'prefix' => "setTimeout(myFunction, ",
                'suffix' => ");",
                'answer' => "2000"
            ],
            'json' => [
                'code' => "let text = '{ \"employees\" : [' +\n'\"{ \"firstName\":\"John\" , \"lastName\":\"Doe\" }\" ]}';\nconst obj = JSON.parse(text);",
                'question' => 'Parse the JSON string named jsonString into a JavaScript object.',
                'prefix' => "let obj = JSON.",
                'suffix' => "(jsonString);",
                'answer' => "parse"
            ],
            'classes' => [
                'code' => "class Car {\n  constructor(name, year) {\n    this.name = name;\n    this.year = year;\n  }\n}",
                'question' => 'Create a class named Car.',
                'prefix' => "",
                'suffix' => " Car {\n  constructor(brand) {\n    this.carname = brand;\n  }\n}",
                'answer' => "class"
            ],
            'fetch' => [
                'code' => "fetch('file.txt')\n  .then(x => x.text())\n  .then(y => document.getElementById('demo').innerHTML = y);",
                'question' => 'Use the fetch API to retrieve "data.txt".',
                'prefix' => "",
                'suffix' => "('data.txt').then(r => r.text());",
                'answer' => "fetch"
            ]
        ];

        return $map[$slug] ?? null;
    }
}
